import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import PrelineScript from "@/components/preline/PrelineScript";

import { cn } from "@/lib/utils";
import StoreProvider from "./StoreProvider";
import { Toast } from "@/components/toast/toast";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Custee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <StoreProvider>
          {children}
          <Toast /> 
        </StoreProvider>
      </body>
      <PrelineScript />
    </html>
  );
}
